###
post http://localhost:4000/admin-api/new-admin
Content-Type: application/json

{
    "adminId":"004",
    "username":"Dedeepya",
    "password":"1234",
    "email":"dedeepya1611@gmail.com",
    "phone":"9866729852"
}

###
post http://localhost:4000/admin-api/login
Content-Type: application/json

{
    "adminId":"004",
    "password":"1234"
}

###
POST http://localhost:4000/admin-api/workshopdata
Content-Type: application/json

{
    "workshopId": "{{$timestamp}}",
    "title": "Blockchain Revolution",
    "topic": "Blockchain technology, cryptography",
    "startDate": "2023-01-20",
    "endDate": "2023-01-20",
    "date": "2023-01-20",
    "location": "VNRVJIET",
    "organizedBy": "VNRVJIET",
    "dateOfCreation": "{{datetime iso8601}}",
    "dateOfModification": "{{datetime iso8601}}",
    "status": true,
    "brochure": "/path/to/brochure.jpg",
    "permissionLetter": "/path/to/permission-letter.pdf",
    "schedule": "/path/to/schedule.docx",
    "resourcePersonsProfile": "/path/to/resource-persons-profile.pdf",
    "listOfParticipants": "/path/to/list-of-participants.xlsx",
    "forms": "/path/to/forms.pdf",
    "attendanceSheets": "/path/to/attendance-sheets.xlsx",
    "expenditureSummary": "/path/to/expenditure-summary.xlsx",
    "feedbackForms": "/path/to/feedback-forms.pdf",
    "photos": "/path/to/photos.pdf",
    "certificate": "/path/to/certificate.jpg",
    "report": "/path/to/report.docx"
}

###
// get sdp data
GET http://localhost:4000/admin-api/workshopdata/993983
